"""empty message

Revision ID: 27026ba8eba8
Revises: 
Create Date: 2020-09-11 20:32:09.492207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27026ba8eba8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('creationData', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Authors', sa.String(length=50), nullable=False),
    sa.Column('Header', sa.String(length=300), nullable=False),
    sa.Column('content', sa.String(length=1500), nullable=False),
    sa.Column('img1', sa.String(length=248), nullable=True),
    sa.Column('creationData', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('postId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['postId'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag')
    op.drop_table('article')
    op.drop_table('Users')
    # ### end Alembic commands ###
